### ISSUE TITLE
写代码务必注意健壮性，不然连抄都没法让人抄。。。

### ISSUE THREAD

**Issue by chihiro2014** [lyj8330328/leyou#9]
`package com.leyou.item.service.impl;

import com.leyou.item.service.SpecificationService;
import com.leyou.item.mapper.SpecificationMapper;
import com.leyou.item.pojo.Specification;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * @Author: 98050
 * Time: 2018-08-14 15:26
 * Feature:
 */
@Service
public class SpecificationServiceImpl implements SpecificationService {

    @Autowired
    private SpecificationMapper specificationMapper;

    @Override
    public Specification queryById(Long id) {
        return this.specificationMapper.selectByPrimaryKey(id);
    }

    @Override
    public void saveSpecification(Specification specification) {
        this.specificationMapper.insert(specification);
    }

    @Override
    public void updateSpecification(Specification specification) {
        this.specificationMapper.updateByPrimaryKeySelective(specification);
    }

    @Override
    public void deleteSpecification(Specification specification) {
        this.specificationMapper.deleteByPrimaryKey(specification);
    }
}`

例如delete这边，明明只需要根据id去删除就ok了。哪有直接传个对象进行删除的？？？
`
public void deleteSpecificationByCategoryId(Long id){
        if (id == null || this.specificationMapper.selectByPrimaryKey(id) == null){
            throw new LyException(ExceptionEnum.ID_DOES_NOT_EXIST);
        }
            this.specificationMapper.deleteByPrimaryKey(id);
    }
`
顺带你controller里面很多错，尽管编译器不一定会报错。然而。。你这逻辑不对十分尴尬

**Comment by lyj8330328** [comment]
> `package com.leyou.item.service.impl;
> 
> import com.leyou.item.service.SpecificationService;
> import com.leyou.item.mapper.SpecificationMapper;
> import com.leyou.item.pojo.Specification;
> import org.springframework.beans.factory.annotation.Autowired;
> import org.springframework.stereotype.Service;
> 
> /**
> 
> * @author: 98050
> * Time: 2018-08-14 15:26
> * Feature:
>   */
>   @service
>   public class SpecificationServiceImpl implements SpecificationService {
>   @Autowired
>   private SpecificationMapper specificationMapper;
>   @override
>   public Specification queryById(Long id) {
>   return this.specificationMapper.selectByPrimaryKey(id);
>   }
>   @override
>   public void saveSpecification(Specification specification) {
>   this.specificationMapper.insert(specification);
>   }
>   @override
>   public void updateSpecification(Specification specification) {
>   this.specificationMapper.updateByPrimaryKeySelective(specification);
>   }
>   @override
>   public void deleteSpecification(Specification specification) {
>   this.specificationMapper.deleteByPrimaryKey(specification);
>   }
>   }`
> 
> 例如delete这边，明明只需要根据id去删除就ok了。哪有直接传个对象进行删除的？？？
> `public void deleteSpecificationByCategoryId(Long id){ if (id == null || this.specificationMapper.selectByPrimaryKey(id) == null){ throw new LyException(ExceptionEnum.ID_DOES_NOT_EXIST); } this.specificationMapper.deleteByPrimaryKey(id); }`
> 顺带你controller里面很多错，尽管编译器不一定会报错。然而。。你这逻辑不对十分尴尬

多谢提醒，希望加q980500807，有些地方还想和你请教一下
